// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductManager.Data;

#nullable disable

namespace ProductManager.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("ProductManager.Data.DepositaryStorage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Depositaries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Location = "Kyiv, UA",
                            Name = "Kyiv Central Hub"
                        },
                        new
                        {
                            Id = 2,
                            Location = "Lviv, UA",
                            Name = "Lviv Tech Warehouse"
                        },
                        new
                        {
                            Id = 3,
                            Location = "Odesa, UA",
                            Name = "Odesa Port Logistics"
                        });
                });

            modelBuilder.Entity("ProductManager.Data.ProductsStorage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DepositoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("PricePerItem")
                        .HasColumnType("REAL");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DepositoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Home",
                            DepositoryId = 1,
                            Description = "Handcrafted scented soy candle with lavender essential oils. Burn time up to 40 hours. Eco-friendly and non-toxic.",
                            Name = "Candle",
                            PricePerItem = 430.0,
                            Quantity = 70
                        },
                        new
                        {
                            Id = 2,
                            Category = "Electronics",
                            DepositoryId = 1,
                            Description = "Industry-leading noise canceling wireless headphones with touch sensor controls and long-lasting 30-hour battery life.",
                            Name = "Sony WH-1000XM4",
                            PricePerItem = 12000.0,
                            Quantity = 12
                        },
                        new
                        {
                            Id = 3,
                            Category = "Electronics",
                            DepositoryId = 1,
                            Description = "Latest model featuring a 6.1-inch Super Retina XDR display, advanced dual-camera system, and the powerful A16 Bionic chip.",
                            Name = "Apple iPhone 15",
                            PricePerItem = 35000.0,
                            Quantity = 25
                        },
                        new
                        {
                            Id = 4,
                            Category = "Gadgets",
                            DepositoryId = 1,
                            Description = "High-resolution 6.8-inch display with adjustable warm light. Waterproof design, perfect for reading by the pool or in the bath.",
                            Name = "Kindle Paperwhite",
                            PricePerItem = 6500.0,
                            Quantity = 40
                        },
                        new
                        {
                            Id = 5,
                            Category = "Accessories",
                            DepositoryId = 1,
                            Description = "Professional wireless mouse designed for ultimate precision. MagSpeed electromagnetic scrolling and ergonomic shape.",
                            Name = "Logitech MX Master 3",
                            PricePerItem = 4200.0,
                            Quantity = 15
                        },
                        new
                        {
                            Id = 6,
                            Category = "Electronics",
                            DepositoryId = 2,
                            Description = "Supercharged by the M2 chip. Features a strikingly thin design, 8-core CPU, and up to 18 hours of battery life.",
                            Name = "MacBook Air M2",
                            PricePerItem = 48000.0,
                            Quantity = 10
                        },
                        new
                        {
                            Id = 7,
                            Category = "Clothing",
                            DepositoryId = 2,
                            Description = "Classic lifestyle sneakers with visible Air-Sole unit for lightweight cushioning and maximum style. Durable rubber outsole.",
                            Name = "Nike Air Max",
                            PricePerItem = 5400.0,
                            Quantity = 30
                        },
                        new
                        {
                            Id = 8,
                            Category = "Storage",
                            DepositoryId = 2,
                            Description = "1TB External Solid State Drive. Transfer massive files in seconds with USB 3.2 Gen 2. Shock-resistant and secure.",
                            Name = "Samsung T7 SSD",
                            PricePerItem = 4800.0,
                            Quantity = 50
                        },
                        new
                        {
                            Id = 9,
                            Category = "Electronics",
                            DepositoryId = 2,
                            Description = "Tenkeyless RGB mechanical gaming keyboard with blue switches for tactile feedback. Built with an aircraft-grade aluminum frame.",
                            Name = "Mechanical Keyboard",
                            PricePerItem = 3200.0,
                            Quantity = 20
                        },
                        new
                        {
                            Id = 10,
                            Category = "Appliances",
                            DepositoryId = 2,
                            Description = "1.7L stainless steel kettle with rapid boil technology and automatic shut-off feature for safety. Modern minimalist design.",
                            Name = "Electric Kettle",
                            PricePerItem = 1800.0,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 11,
                            Category = "Electronics",
                            DepositoryId = 3,
                            Description = "Powerful portable Bluetooth speaker with IP67 waterproof and dustproof rating. Delivers loud, crystal clear sound anywhere.",
                            Name = "JBL Flip 6",
                            PricePerItem = 4500.0,
                            Quantity = 22
                        },
                        new
                        {
                            Id = 12,
                            Category = "Appliances",
                            DepositoryId = 3,
                            Description = "Semi-automatic espresso machine with a high-pressure pump and built-in milk frother. Perfect for lattes and cappuccinos.",
                            Name = "Coffee Maker",
                            PricePerItem = 7500.0,
                            Quantity = 8
                        },
                        new
                        {
                            Id = 13,
                            Category = "Accessories",
                            DepositoryId = 3,
                            Description = "Anti-theft business backpack with hidden zippers, integrated USB charging port, and water-repellent fabric.",
                            Name = "Backpack Antitheft",
                            PricePerItem = 2300.0,
                            Quantity = 60
                        },
                        new
                        {
                            Id = 14,
                            Category = "Electronics",
                            DepositoryId = 3,
                            Description = "Advanced smartwatch with health tracking, GPS, and a vibrant AMOLED display. Monitors heart rate, sleep, and blood oxygen levels.",
                            Name = "Smart Watch",
                            PricePerItem = 9000.0,
                            Quantity = 18
                        });
                });

            modelBuilder.Entity("ProductManager.Data.ProductsStorage", b =>
                {
                    b.HasOne("ProductManager.Data.DepositaryStorage", "Depository")
                        .WithMany("Products")
                        .HasForeignKey("DepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Depository");
                });

            modelBuilder.Entity("ProductManager.Data.DepositaryStorage", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
